"""Initial migration

Revision ID: eb975098eb01
Revises: 
Create Date: 2025-12-02 22:11:22.538746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb975098eb01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=50), nullable=False),
    sa.Column('lastName', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('lectures',
    sa.Column('lid', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('lid')
    )
    op.create_table('attendance',
    sa.Column('aid', sa.Integer(), nullable=False),
    sa.Column('lecture_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('attendance', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['lecture_id'], ['lectures.lid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('aid')
    )
    op.create_table('lecture_enrollment',
    sa.Column('leid', sa.Integer(), nullable=False),
    sa.Column('lecture_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('room_assigned', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['lecture_id'], ['lectures.lid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('leid')
    )
    op.create_table('lecture_rooms',
    sa.Column('lrid', sa.Integer(), nullable=False),
    sa.Column('lecture_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lecture_id'], ['lectures.lid'], ),
    sa.PrimaryKeyConstraint('lrid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lecture_rooms')
    op.drop_table('lecture_enrollment')
    op.drop_table('attendance')
    op.drop_table('lectures')
    op.drop_table('users')
    # ### end Alembic commands ###
