"""Add LectureRooms and update LectureEnrollment

Revision ID: 0ec39e0c88b2
Revises: ce0ba43b3087
Create Date: 2025-12-02 12:35:53.658279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ec39e0c88b2'
down_revision = 'ce0ba43b3087'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('aid', sa.Integer(), nullable=False),
    sa.Column('lecture_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('attendance', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['lecture_id'], ['lectures.lid'], ),
    sa.PrimaryKeyConstraint('aid')
    )
    op.create_table('lecture_rooms',
    sa.Column('lrid', sa.Integer(), nullable=False),
    sa.Column('lecture_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lecture_id'], ['lectures.lid'], ),
    sa.PrimaryKeyConstraint('lrid')
    )
    with op.batch_alter_table('lecture_enrollment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_assigned', sa.String(length=100), nullable=True))
        batch_op.create_foreign_key(None, 'lectures', ['lecture_id'], ['lid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lecture_enrollment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('room_assigned')

    op.drop_table('lecture_rooms')
    op.drop_table('attendance')
    # ### end Alembic commands ###
