"""empty message

Revision ID: ce0ba43b3087
Revises: 910976989607
Create Date: 2025-11-23 14:56:53.679606

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ce0ba43b3087'
down_revision = '910976989607'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lecture_enrollment',
    sa.Column('leid', sa.Integer(), nullable=False),
    sa.Column('lecture_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('leid')
    )
    op.create_table('lectures',
    sa.Column('lid', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('lid')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('firstName',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('firstName',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)

    op.drop_table('lectures')
    op.drop_table('lecture_enrollment')
    # ### end Alembic commands ###
